"""add_indexes_to_payments_and_outbox

Revision ID: 03ef0a6799bc
Revises: f8ed48433421
Create Date: 2026-04-23 08:40:33.583598

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03ef0a6799bc'
down_revision: Union[str, Sequence[str], None] = 'f8ed48433421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outbox_processed'), 'outbox', ['processed'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_outbox_processed'), table_name='outbox')
    # ### end Alembic commands ###
