"""add_index_to_outbox_created_at

Revision ID: 7bc0a9014394
Revises: 03ef0a6799bc
Create Date: 2026-04-23 09:12:48.736709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7bc0a9014394'
down_revision: Union[str, Sequence[str], None] = '03ef0a6799bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outbox_created_at'), 'outbox', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_created_at'), table_name='outbox')
    # ### end Alembic commands ###
